### ISSUE TITLE
Update the UI for collection widgets - list update, reposition buttons

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#142] opened 2012-01-11 07:07 UTC
- `3 hours`  - New item list UI with selectable and drag & drop: http://jsbin.com/aweyo5
- Instead of a menu, we have a toolbar on top with the following:
  - back button icon- | -new folder icon- -new page icon- | -rename- -edit- | -delete-
  - Since items can be reordered by drag and drop, we don't need the up/down arrows anymore.

**Comment by gilbert** [comment] 2012-01-11 20:18
This is a duplicate of #132

**Closed as completed by gilbert** 2012-01-11 20:18 UTC
Labels: Feature Request, Approved, Discussion
